### PR TITLE
Milestone 2 code review request

### PR DESCRIPTION
**Pull request by Rashad-Muntar**
Milestone 2 user interface for Tic Tac Toe game
 # We took user symbol and name
 # We displayed user game introduction
# We automatically assign a symbol to the player after 2 wrong attempts.
# The symbol for player 2 is automatically assigned base on the option chosen by player 1
# Displayed that game has started

### CODE REVIEW

**Review by smcommits — COMMENTED** [review]
# Status: PR Invalid:exclamation:

Friendly reminder: Please make sure that you are passing all the linter checks before requesting a review. You have multiple checks that are failing. 
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

# 
Any further questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi team!
Nice one on adding a very descriptive readme:clap::clap:. Let's fix the game so it can start working as expected.**
Currently, there's no board been displayed and as such no game to play. Kindly follow the steps outlined below to get the game working.

- [x] the game asks the player to select from available moves.  Players will be able to make a move between 1....9 or 0....8  depending on the implementation.

- [x] the game informs the player if the selected move is invalid (without computing what an invalid move is). Once a move is made, We cannot reenter that move, else the game raises an invalid move.

- [x] The game displays the board after the player move (without computing which spots on the board are taken). Add the board to account for this.

- [x] the game informs the player if the selected move is a winning move (without computing the winning move). The game should be able to display say the winner is 'X' no matter who won.

- [x] the game informs the player if the selected move is a draw move (without computing draw). The game should display a draw if there is a tie.

- [x] the game repeats all actions for the next player's move

- [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))

make the above-required changes and when you are ready, request another review.
You can drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.

Happy Coding:blush:
Eric Enaburekhan

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Diegodsha and @Rashad-Muntar 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Kindly work on previous TSE Suggestions.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] It has a descriptive branch name 💯

- ### To Improve
  - [x] [MANDATORY] The main.rb doesn't have a UI for this situation:
    - when a player makes invalid move.
  - [x] [OPTIONAL] I strongly recommend using functions to make this codebase readable and very easyly managable.

- ### Note
  - Remember, the logic doesn't need to work.   


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by enaburekhan — APPROVED** [review]
# Status: Project Approved:heavy_check_mark:
**Hi team!
Nice one:clap::clap:. The game is working as expected. keep up the good work:thumbsup:. 
Move on with your next task:walking:.**

You can drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan.

**Pull request closed without merging**
